### ISSUE TITLE
Link repository to hub.docker.com

### ISSUE THREAD

**Issue by fernwerker** [jenningsloy318/redfish_exporter#17]
Is it possible to link the repository to hub.docker.com.
I could do it myself, but only with a fork. I'd prefer to have the repository directly be connected to hub.docker.com

E.g. following: https://medium.com/@_oleksii_/set-up-automated-builds-using-github-and-docker-hub-12c3e0f18eba
Thanks.

**Comment by jenningsloy318** [comment]
This docker image is used to build the binary,you can pull it from 
```
docker pull jenningsloy318/prom-builder
```

You can simply build it with 
```
make docker-build
```

**Comment by fernwerker** [comment]
Don't know if I get this right. What does the prom-builder include?
I don't want to build myself, I'd like to use a CI/CD chain by hub.docker.com and let their ressources automatically build the images from the github repository and offer it within hub.docker.com
