### ISSUE TITLE
Docker Image not working properly

### ISSUE THREAD

**Issue by Lars2206** [jenningsloy318/redfish_exporter#18]
I've build the Docker Image with the Dockerfile and tried to start it with the Argument config.file=...., ut it keeps failing
`Failure
OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"--config.file=/etc/redfish_exporter/redfish_exporter.yml\": stat --config.file=/etc/redfish_exporter/redfish_exporter.yml: no such file or directory": unknown`
I've bind the volume with the config file to the right place (can find it in the interactive terminal)

When i dont pass the config nothing happens at all (no error, no running process, nothing) the only thing that appears in the log is:
`]0;@990ef5db40b5:/[root@990ef5db40b5 /]# `

I also didnt find an entry point (executable with name ~redfish_exporter) in the image, but this could be my fault.

Has anbody else has similar Problems?
[redfish_exporter_dockerconfig.txt](https://github.com/jenningsloy318/redfish_exporter/files/4960044/redfish_exporter_dockerconfig.txt)

**Comment by jenningsloy318** [comment]
Hello,this dockerfile is only used for build binary,not running the binary ,you should run binary directly
