### ISSUE TITLE
offer help in maintaining this prometheus exporter

### ISSUE THREAD

**Issue by mjavier2k** [jenningsloy318/redfish_exporter#22]
Hi, 

We are a new user of this Prometheus exporter and would like to offer help in maintaining and enhancing this exporter if needed. We intent to make great use of this exporter as it solves a big pain point for us

Thanks,
Marvin

**Comment by jenningsloy318** [comment]
Hi @mjavier2k 

very glad to hear that, any advices and pull requests are really appreciated.
