### ISSUE TITLE
Tagging new releases?

### ISSUE THREAD

**Issue by neufeldtech** [jenningsloy318/redfish_exporter#24]
Hey there @jenningsloy318 ,

We've been using this exporter and finding it very useful. However, in order to get it working correctly we needed to build it from the source from the latest code to get all bugfixes and enhancements.

Do you have plans to keep tagging releases to keep them up to date with recent patches and development?

**Comment by jenningsloy318** [comment]
Hi @neufeldtech 

I will create a new release later,  thanks for your reminding

**Comment by jenningsloy318** [comment]
Hi @neufeldtech  

I published a new version 0.11.0, you can grab them in the release page
