### ISSUE TITLE
ChassiCollector & SystemCollector- Error Scraping

### ISSUE THREAD

**Issue by RyanW8** [jenningsloy318/redfish_exporter#25]
Hey getting this error

`2020/11/23 17:18:30 error error getting power data from chassis Chassis=Self app=redfish_exporter collector=ChassisCollector error=json: cannot unmarshal number into Go struct field PowerControl.PowerControl.MemberId of type string operation=chassis.Power() target=REDACTED`

As well as 

`2020/11/23 17:20:46 error error getting processor data from system System=Self app=redfish_exporter collector=SystemCollector error=json: cannot unmarshal string into Go struct field .MaxSpeedMHz of type int operation=system.Processors() target=REDACTED`
Any idea on what it could be?

**Comment by RyanW8** [comment]
Also seems that scraping data is taking an extremely long time... I've only got 2 hosts hooked up atm (one is returning a 401 unauthorized instantly and the other is this host).

**Comment by jenningsloy318** [comment]
Hi,

Can you use curl to get what exactly data for PowerControl.PowerControl and MaxSpeedMHz as json  and paste the output here?

**Comment by RyanW8** [comment]
What's the exact endpoint I have to curl to get that?

**Comment by RyanW8** [comment]
https://gist.github.com/RyanW8/42803cee457e5ebe6d198a2141224be6 This is for PowerControl Grabbed using `https://<host_ip>/redfish/v1/Chassis/Self/Power`. Looks to be that some MemberIDs are strings and some are numbers

https://gist.github.com/RyanW8/74c4904706b486e0862703d96c5f9235 This is the CPU information. Grabbed using `https://<host_ip>/redfish/v1/System/Self/Processors/1` & `https://<host_ip>/redfish/v1/System/Self/Processors/2`. Looks like MaxSpeedMHz isn't set.

**Comment by RyanW8** [comment]
https://github.com/stmcginnis/gofish/pull/100 I raised the issue upstream and they've made a PR to fix the handling of it

**Comment by jenningsloy318** [comment]
Hi Ryan,

I update the dependency, as this is just upstream fix, will not publish a new release, you can grab the code and build it on your side.

**Comment by jenningsloy318** [comment]
@RyanW8  is this issue fixed ?
