### ISSUE TITLE
cannot unmarshal number into Go struct field .Socket of type string operation=system.Processors() 

### ISSUE THREAD

**Issue by jacobawy** [jenningsloy318/redfish_exporter#27]
2021/02/04 15:02:24  info collector scrape started  Chassis=RootService app=redfish_exporter collector=ChassisCollector target=xxxxxx
2021/02/04 15:02:24  info no thermal data found     Chassis=RootService app=redfish_exporter collector=ChassisCollector operation=chassis.Thermal() target=1xxxxx
2021/02/04 15:02:24  info no power data found       Chassis=RootService app=redfish_exporter collector=ChassisCollector operation=chassis.Power() target=xxxxx
2021/02/04 15:02:25  info collector scrape started  Manager=1 app=redfish_exporter collector=ManagerCollector target=xxxxx
2021/02/04 15:02:25  info collector scrape completed Manager=1 app=redfish_exporter collector=ManagerCollector target=xxxxx
2021/02/04 15:02:25  info collector scrape started  System=1 app=redfish_exporter collector=SystemCollector target=xxxx
2021/02/04 15:02:25  info no network adapters data found Chassis=RootService app=redfish_exporter collector=ChassisCollector operation=chassis.NetworkAdapters() target=
2021/02/04 15:02:25  info collector scrape completed Chassis=RootService app=redfish_exporter collector=ChassisCollector target=xxxxx
2021/02/04 15:02:28 error error getting processor data from system System=1 app=redfish_exporter collector=SystemCollector error=json: cannot unmarshal number into Go struct field .Socket of type string operation=system.Processors() target=

**Comment by stmcginnis** [comment]
Not sure where this is coming from, but just an observation.

"cannot unmarshal number into Go struct field .Socket of type string"

This may be a problem with the Redfish implementation on the device being scraped. Based on the above error, it would appear it is returning an integer result for the Processor's Socket property. The Redfish specification specifically calls this property out as a string value:

> This property shall contain the string that identifies the physical location or socket of the processor.

Just pointing that out in case it helps troubleshoot in any way.

**Comment by jacobawy** [comment]
Is it related to it being an inspur server

**Comment by jenningsloy318** [comment]
@jacobawy  can you post full output for the chassis and its sub-components data here ?

**Comment by jenningsloy318** [comment]
close this as it is not update for long time.
