### ISSUE TITLE
Error getting credentialfor target 10.10.10.2 file: no credentials found for target 10.10.10.2

### ISSUE THREAD

**Issue by matejzero** [jenningsloy318/redfish_exporter#3]
I'm getting the error in the title and I don't know what I'm doing wrong.

My config.yaml looks like:
```yaml
hosts:
  10.10.10.2:
    username: monitor
    password: bbccbbcc
```

and I start the exporter with `./redfish_exporter  --config.file="/root/config.yaml"`. I then call http://home.example.org:9610/redfish?target=10.10.10.2 and get the error in the title in the console.

```
INFO[0000] redfish_exporter version 0.10.1, build reversion 56a0ceab10f9632997f1c4b6b08c51c7e80ab94d, build branch master, build at Fri Oct 25 12:24:23 DST 2019 on host CTUN50947963A    source="main.go:65"
INFO[0000] Starting redfish_exporter                     source="main.go:72"
INFO[0000] Loaded config file                            source="config.go:42"
INFO[0000] Listening on :9610                            source="main.go:97"
INFO[0005] Scraping target 10.10.10.2               source="main.go:37"
FATA[0005] Error getting credentialfor target 10.10.10.2 file: no credentials found for target 10.10.10.2  source="main.go:42"
```

What am I doing wrong? I noticed the same issue already closed but no solution.

Thanks, Matej

**Comment by jenningsloy318** [comment]
Hi,does you account have admin permission?

**Comment by matejzero** [comment]
No, it has only read-only permissions.

**Comment by jenningsloy318** [comment]
Can you try to add admin permission?as some info retrieved by redfish should have admin permission.

**Comment by matejzero** [comment]
Looking at the [code](https://github.com/jenningsloy318/redfish_exporter/blob/c014da50d27d4fef5adb89c84da0a9a1b836f5e5/main.go#L45), this error happens before any request is sent to Redfish.

**Comment by jenningsloy318** [comment]
Can you try to rename the IP to default in the redfish config? This code is to search the corresponding credentials from it,if not found ,it will use default ?

**Comment by matejzero** [comment]
I updated the config, but still the same error:/

```yaml
hosts:
  10.10.10.2:
    username: monitor
    password: bbccbbcc
  host.example.org:
    username: monitor
    password: bbccbbcc
  default:
    username: monitor
    password: bbccbbcc
```

I also noticed I'm using the latest release (0.10.1). I might have to pull down master branch and recompile?

**Comment by jenningsloy318** [comment]
Maybe you can build it at your side,later I will check at my side ?

**Comment by matejzero** [comment]
Yea I’ll rebuild  it tomorrow and report back.

Thanks.

On 25 Apr 2020, at 02:24, jenningsloy318 <notifications@github.com> wrote:

﻿

Maybe you can build it at your side,later I will check at my side ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jenningsloy318/redfish_exporter/issues/3#issuecomment-619289799>,
or unsubscribe

**Comment by jenningsloy318** [comment]
Hi, I will check the code, seems my last update break something

**Comment by matejzero** [comment]
It works when built from master branch.
