### ISSUE TITLE
Unable to create Docker image

### ISSUE THREAD

**Issue by deepankersharmaa** [jenningsloy318/redfish_exporter#31]
Hi can you please help me to create docker image.
Please share proper steps.

getting below error...

Complete!
fatal: not a git repository (or any parent up to mount point /go/src/github.com/jenningsloy318)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /go/src/github.com/jenningsloy318)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by jenningsloy318** [comment]
```curl http://localhost:9610/redfish?target=172.17.40.250```
- if `172.17.40.250` is you ip address of the PowerEdge R730 server ?
- check your  configuration for 172.17.40.250, did you add the config as the readme examples ? if possible, paste your config here, please. 
- please make sure to create a proper user/password for redfish-exporter to extract info from you server
