### ISSUE TITLE
hostname is null

### ISSUE THREAD

**Issue by vince-weka** [jenningsloy318/redfish_exporter#32]
The hostname is coming up null on a supermicro server:

redfish_system_memory_state{**hostname=""**,memory="P1-DIMMA1",memory_id="1",resource="memory"} 1

I've set the hostname via the IPMI interface.

**Comment by jenningsloy318** [comment]
Hi
can you please get the  json response from the api, not sure if it is configured in other place.

**Comment by vince-weka** [comment]
What field/url are you using for hostname?  This server lists the name in /redfish/v1/Managers/1/EthernetInterfaces/1

**Comment by jenningsloy318** [comment]
under sysrem/hostname，not individual component，It is the standard redfish specification, please check if your sever have fully compatibility with redfish specification
