### ISSUE TITLE
Endpoint to trigger configuration reload

### ISSUE THREAD

**Issue by mehyedes** [jenningsloy318/redfish_exporter#35]
Hi, 

I see it is possible to trigger a configuration reload by sending a `SIGHUP` to the process.

I think adding an HTTP endpoint for reloading the configuration like `/-/reload` for [prometheus](https://prometheus.io/docs/prometheus/latest/configuration/configuration/) would be also useful IMO.

If you agree, I could work on adding this feature myself.

**Comment by jenningsloy318** [comment]
Hi @mehyedes 

Thanks for your enthusiasm, any contribution is welcome. and you can go ahead add this feature. 

Thanks

**Comment by mehyedes** [comment]
Great, thanks.
I'll get working on that and submit a PR as soon as it's ready.
