### ISSUE TITLE
deps rule missing from Makefile

### ISSUE THREAD

**Issue by sbates130272** [jenningsloy318/redfish_exporter#5]
Nice tool! But I see that the ```deps``` target specified on the ```all:``` rule of the Makefile has no rule in the Makefile? I was able to fix this with a 
```
go get
```
before running ```make``` but I suspect we want to fix this in the Makefile?

**Comment by jenningsloy318** [comment]
Hi @sbates130272, I updated Makefile, remove some of them, as I did't do such jobs. 

since it uses go mod to ensure the dependency, so I will not add them into Makefile
