### ISSUE TITLE
processors: json: cannot unmarshal object into Go struct field .Metrics of type string

### ISSUE THREAD

**Issue by matejzero** [jenningsloy318/redfish_exporter#9]
While running the exporter, I also get the following error: `Errors Getting Processors from system: json: cannot unmarshal object into Go struct field .Metrics of type string  source="system_collector.go:403"`

Processors .Metrics field in my case (Lenovo SR630) is not a string:

```json
{
    "ProcessorArchitecture": "x86",
    "Metrics": {
        "@odata.id": "/redfish/v1/Systems/1/Processors/1/ProcessorMetrics"
    },
...
```

Dell server doesn't even report Metrics resource.

**Comment by jenningsloy318** [comment]
@matejzero  created a issue on upstream https://github.com/stmcginnis/gofish/issues/61, will try to fix it once there is a update

**Comment by jenningsloy318** [comment]
@matejzero  Please grab the latest source code, build the binary and then test if the issue is fixed

**Comment by matejzero** [comment]
This is fixed and works on Lenovo servers.
